"""Execute python tool."""

from __future__ import annotations

import contextlib
import functools
import io
import traceback
from typing import Any

import numpy as np

from .bm25_search import search_terms
from .distance import get_distance
from .search_around import search_around_component
from .component_info import get_component_info

def execute_python(code: str, dataset_name: str | None = None) -> dict[str, Any]:
    """
    Execute a python program generated by the LLM in a sandbox.
    
    Args:
        code: The python code to execute.
        dataset_name: Dataset to run tools against.
        
    Returns:
        A dictionary containing 'output' (stdout) and 'error' (traceback if any).
    """
    # Set up the sandbox environment
    sandbox_globals = {
        "__builtins__": __builtins__,
        "np": np,
        "search_terms": functools.partial(search_terms, dataset_name=dataset_name),
        "get_distance": functools.partial(get_distance, dataset_name=dataset_name),
        "search_around_component": functools.partial(search_around_component, dataset_name=dataset_name),
        "get_component_info": functools.partial(get_component_info, dataset_name=dataset_name),
    }
    
    # Capture stdout
    stdout_capture = io.StringIO()
    error_msg = None
    
    try:
        with contextlib.redirect_stdout(stdout_capture):
            # We use exec to run the code.
            # We provide sandbox_globals as the globals and a new dict for locals
            # to avoid polluting the globals and to capture any variables created.
            exec(code, sandbox_globals, {})
    except Exception:
        error_msg = traceback.format_exc()
        
    return {
        "output": stdout_capture.getvalue(),
        "error": error_msg
    }

EXECUTE_PYTHON_TOOL = {
    "type": "function",
    "name": "execute_python",
    "description": (
        "Execute a python program in a sandboxed environment. "
        "Useful for performing complex logic, calculations, or multi-step reasoning."
    ),
    "parameters": {
        "type": "object",
        "properties": {
            "code": {
                "type": "string",
                "description": "The pure Python code to execute. Do NOT include markdown code block syntax (like ```python). Use print() to output results.",
            },
        },
        "required": ["code"],
        "additionalProperties": False,
    },
}

EXECUTE_PYTHON_THINKING_TEXT = "Executing python code..."

EXECUTE_PYTHON_DESCRIPTION = """- **Python Execution Tool:** Use `execute_python` to run python code.
  - The code runs in a sandbox with the following functions pre-imported and available globally (no imports needed):
    - `search_terms(query_terms: list[str], top_k: int = 10) -> dict` 
      Returns: `{"results": [{"component_id": int, "caption": str, "bbox": dict, "score": float}, ...]}`
    - `get_distance(component_id_1: int, component_id_2: int) -> dict`
      Returns: `{"distance": float}` (distance in meters)
    - `search_around_component(component_id: int, radius: float, search_term: str = None, direction: str = None) -> dict`
      Returns: `{"components": [{"id": int, "caption": str, "bbox": dict}, ...], "reason": str}`
    - `get_component_info(component_id: int) -> dict`
      Returns: `{"component_id": int, "caption": str, "best_crop": str, "bbox": dict}`
  - `numpy` is also pre-imported as `np`.
  - The result returned will be whatever is printed to standard output (`stdout`), so make sure to use `print()` for any results you want to see. If there is an error, the traceback will be returned.
  - You do not need to provide `dataset_name` when calling the pre-imported tools; it is handled automatically.
  - Do NOT wrap the code in markdown formatting (like ```python ... ```), just provide pure python code."""
